apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
spec:
  selector:
    matchLabels:
      app: APP_NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
      - name: APP_NAME
        image: projectakscr.azurecr.io/IMAGE_NAME:VERSION
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
spec:
  selector:
    app: APP_NAME
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer

