apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiapp
spec:
  selector:
    matchLabels:
      app: apiapp
  replicas: 1
  template:
    metadata:
      labels:
        app: apiapp
    spec:
      containers:
      - name: apiapp
        image: projectakscr.azurecr.io/api2:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: apiapp
spec:
  selector:
    app: apiapp
  ports:
  - name: backend-api-port      
    port: 8090
    targetPort: 8090
  type: LoadBalancer
